name: Update Website
on:
  push:
    branch:
      - master

jobs:
  build:
    name: Deploy Website
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: |-
        npm install --no-optional
        npm install -g hexo-cli
    - name: Prepare before deploy
      run: |-
        git config --global user.name "syntony666"
        git config --global user.email syntony666@github.com
    - name: Depoly to GitHub Page
      run: hexo d -g
